export class User {
  constructor(
    public avatarUrl: string = '',
    public eventsUrl: string = '',
    public followersUrl: string = '',
    public followingUrl: string = '',
    public gistsUrl: string = '',
    public gravatarid: string = '',
    public htmlUrl: string = '',
    public id: number = 0,
    public login: string = '',
    public nodeId: string = '',
    public organizationsUrl: string = '',
    public receivedEventsUrl: string = '',
    public reposUrl: string = '',
    public score: number = 0,
    public siteAdmin: boolean = null,
    public starredUrl: string = '',
    public subscriptionUrl: string = '',
    public type: string = '',
    public url: string = '',
    public bio: string = '',
    public blog: string = '',
    public company: string = '',
    public createdAt: string = '',
    public email: string = '',
    public followers: number = null,
    public following: string = null,
    public hireable = 'true',
    public location: string = '',
    public name: string = '',
    public publicGists: number = null,
    public publicRepos: number = null,
    public updatedAt: string = '',
  ) {}
}
